### ISSUE TITLE
[Suggeston] Include the 6 decimal places when using Mrai as units, so more precise amount can be sent

### ISSUE THREAD

**Issue by RaiBlocksDisciple** [nanocurrency/raiblocks#117] opened 2017-05-04 01:03 UTC
Would be more convenient / useful as currently the only way to send precise amounts is to use rai as units. Possibly more useful if value of Mrai increases significantly.

i.e it is not possible to send 1000.543212 Mrai if Mrai are the default units, only 1000 Mrai can be sent.

Similar suggestion for krai too, include the 3dp. 

Or just have it available as an option which can be turned off if people don't like the decimals.
But being able to send precise amounts using Mrai as default units is a must, in my opinion.

**Comment by zhyatt** [comment] 2018-12-27 17:00
Closing out as duplicate of https://github.com/nanocurrency/raiblocks/pull/1301

**Closed by zhyatt** 2018-12-27 17:00 UTC
