### ISSUE TITLE
Ubuntu PPA for wallet and possibly other tools?

### ISSUE THREAD

**Issue by IvanAnishchuk** [nanocurrency/raiblocks#343] opened 2017-12-31 10:12 UTC
Could really help with adoption, I believe... Something for other distros too (ebuilds for gentoo, AUR for arch, etc.), but I can't help with that as I'm on ubuntu myself.

**Comment by androm3da** [comment] 2017-12-31 18:51
There is an AUR already, feel free to make a PPA.

**Comment by nikodean1** [comment] 2018-04-17 23:42
Hi. I can't get rai_wallet (the official Nano wallet/node software for Linux) to run on Gentoo 2018 (AMD64). It says 'Illegal Instruction' when I try to run it.

What can I do to make it work?

**Comment by rkeene** [comment] 2018-08-23 17:09
Duplicate of #12

**Closed by rkeene** 2018-08-23 17:09 UTC
