### ISSUE TITLE
RPC callback block field is a string and not an object

### ISSUE THREAD

**Issue by NiFNi** [nanocurrency/raiblocks#749] opened 2018-03-23 22:31 UTC
**Description of bug:**

The RPC callback does send the block field as a string. So for example:

 ```
"block": "{\n    \"type\": \"receive\",\n    \"previous\": \"180EFCCCF87025CCC3C4DCB5FA4769004C702DB720B18537262AEC48C74D4189\",\n    \"source\": \"723DA447BD9BDA1892B4090544990722328F5000537956DFD7475A679FFD8249\",\n    \"work\": \"d56656b3f2f2fb6d\",\n    \"signature\": \"15DE8F4A01D6AAA2997BBCD3B14783EAA8CFF636A9B4EA8A7F3F6A8D79755746C301FC0590567FA62A18AADBBFAD04E466018445BF20A4CBA93204CC1E471B0E\"\n}\n"
```

In the wiki it is shown as JSON-object. So the same example should be like this:

```
"block": {"type": "receive", "previous": "180EFCCCF87025CCC3C4DCB5FA4769004C702DB720B18537262AEC48C74D4189", "source": "723DA447BD9BDA1892B4090544990722328F5000537956DFD7475A679FFD8249", "work": "d56656b3f2f2fb6d", "signature": "15DE8F4A01D6AAA2997BBCD3B14783EAA8CFF636A9B4EA8A7F3F6A8D79755746C301FC0590567FA62A18AADBBFAD04E466018445BF20A4CBA93204CC1E471B0E"}"
```

I like approach using JSON-objects seems more like what one would expect in my opinion. Is there a specific reason for it being a string? If not what about changing it to return an object by default while still being able to use the "legacy" mode for backwards compatibility by setting something in the config?

**Comment by NiFNi** [comment] 2018-03-23 22:52
Same applies for retrieving a block over the RPC. This results in bad code on the listener side when using automatic JSON to object mapping. Simple Kotlin example with json_response being the body of the result of the rpc call:
```
data class NanoBlock(val type: String, val previous: String, val destination: String,
                     val balance: String, val work: String, val signature: String)

data class NanoBlockStringWrapper(val contents: String)

val wrapped: NanoBlockStringWrapper = jacksonObjectMapper().readValue(json_response)
val validated: NanoBlock = jacksonObjectMapper().readValue(wrapped.contents)
```

**Comment by termhn** [comment] 2018-03-23 23:43
I believe it's a string because that's the format that the RPC `process` command (and other ones that expect a fully rendered block as input) expects.

**Comment by pocesar** [comment] 2018-03-24 00:20
it's actually a problem with the Boost library that doesn't (or is an expensive operation) to do nested object serialization. so it just outputs the JSON string as-is (there was a discussion about this, but I couldn't find)

**Comment by clemahieu** [comment] 2018-03-24 00:21
Yea we need to swap out the Jason serialization library or if someone wants to contribute that.

**Comment by rkeene** [comment] 2018-08-23 18:38
I'm closing this ticket as a duplicate of #499 so that we can track the specific needed changes individually.

**Closed by rkeene** 2018-08-23 18:38 UTC
