### ISSUE TITLE
Mixed RPC return types

### ISSUE THREAD

**Issue by acudworth** [nanocurrency/raiblocks#617] opened 2018-02-14 15:18 UTC
The `pending` RPC call returns an empty string when there are no pending blocks but returns an object (with hashes as values) when there are pending blocks. 

It would be more appropriate to return an empty object `{}` when there are no pending blocks.

Assuming this happens for other RPC calls too..

**Comment by PlasmaPower** [comment] 2018-02-14 15:19
See also: #499. We'll need a new JSON library to fix this.

**Comment by rkeene** [comment] 2018-08-23 18:09
Closing this as a duplicate of #499

**Closed by rkeene** 2018-08-23 18:09 UTC
