### ISSUE TITLE
the network is unresponsive when using rai-9.0.0-Linux

### ISSUE THREAD

**Issue by chubin** [nanocurrency/raiblocks#327] opened 2017-12-29 18:26 UTC
I have observed the following strange behavior: when rai-9.0.0-Linux is started, the network becomes unresponsive (for example ping rtt to 8.8.8.8 is 5000 ms). As soon as the rai wallet is close, everything becomes just normal (rtt to 8.8.8.8 10ms). (trafshow shows nothing special, just some low traffic; synchronization is finished).

**Comment by androm3da** [comment] 2017-12-29 18:30
I suspect that this is expected behavior.  Note that the disk I/O from the raiblocks wallet can be another cause of network latency beyond just the synchronization network traffic.

**Comment by chubin** [comment] 2017-12-29 18:33
Strange, that there is no or almost no traffic on the interface at the moment.
Regarding the disk I/O, everything else works just fine (I should try to ping loopback and something in the local network; I'm curious if it works).

**Comment by bmharper** [comment] 2017-12-31 07:56
I have observed the same thing. My entire home network becomes unusable when rai_wallet 9 is running. Building latest from master.

**Comment by chubin** [comment] 2017-12-31 08:23
I've found a workaround.
I think that the problem is with the router or better to say with the device, that make NAT.
It has (I assume) limited network address translation capacity, and if too many addresses (address pairs) have to be translated, the translation tables gets overflow, and traffic starts being dropped.
My workaround:
I started a VPN connection from the host where the wallet is running to an external host,
and the problem disappeared indeed. @bmharper I suggest you do the same.

**Comment by bmharper** [comment] 2017-12-31 08:52
hah! I thought this might be the problem!
Great idea on the VPN. But... this is a problem that needs to be fixed in the software. I don't know enough about UDP to know what the root cause is here.

**Comment by chubin** [comment] 2017-12-31 09:59
@bmharper Why do you think that it should be fixed? I would say it is just normal. If you generate many address pairs (basically if you communicate with many peers) it is possible that your translation table will be overflowed. The only thing that could be done on the wallet side is to add some configurable artificial limitation like a limit of peers.

**Comment by hacki11** [comment] 2018-01-01 21:23
can confirm for v9 and windows8
running wallet on pc will bring internet connection for complete network down
closing the wallet and the connection is fine after a few seconds

connections should be limited in software to be able to use without the use of vpn

**Comment by bmharper** [comment] 2018-01-02 07:57
@chubin I'd say that this should be fixed, because software needs to "just work", and not cause unwanted side effects, such as disabling a person's internet connection. There is definitely a way to make it work without bringing down the user's network. Skype, BitTorrent, etc, all achieve this.

**Comment by chubin** [comment] 2018-01-02 11:14
@bmharper I would say you are right, the only point that I want to note, that the problem occurs not always, but only in cases when the NAT device (it is a home router usually) is not good enough and can't handle too many addresses

**Comment by hacki11** [comment] 2018-01-02 11:25
@chubin for users where the internet-provider provides the router hardware you can expect cheap hardware where this will be the case. I can not say for everywhere, but in germany it is pretty common to use the provided hardware. so i would say it would hit much more people than it is expected.

think of adoption problems for "normal" users

**Comment by chubin** [comment] 2018-01-02 11:36
@hacki11 Yes, I understand it. I agree with you guys. The more people are supported and happy the better (und in solchen Fällen wo die Hardware von dem Anbieter kommt, kann man im Prinzip einen extra Router kaufen). But as I said: I agree with you (and for the first time we have the "VPN workaround").

**Closed** 2018-05-13 13:35 UTC
