### ISSUE TITLE
Cannot lock wallet

### ISSUE THREAD

**Issue by ghost** [nanocurrency/raiblocks#288] opened 2017-12-26 23:24 UTC

**Comment by SergiySW** [comment] 2017-12-26 23:30
Press "Lock" without password. People often tried to set password with that field

**Comment by Vladlak** [comment] 2017-12-26 23:33
Ahh this seems to work, if you press lock without password it locks it
if you press it with a password you get an error message

**Comment by dannyvankooten** [comment] 2017-12-27 10:32
Duplicate of #279, but as @SergiySW most likely just an UX issue and not a bug.

**Closed** 2018-05-13 13:32 UTC
