### ISSUE TITLE
Docker image not starting

### ISSUE THREAD

**Issue by bbozo** [nanocurrency/raiblocks#496] opened 2018-01-15 08:03 UTC
**Description of bug:**

The error is:

```
$ docker run -d -p 7075:7075/udp -p 7075:7075 -p [::1]:7076:7076 -v ~:/root clemahieu/rai_node /rai_node --daemon
dffb8401f8f88c2d1abf2e14ed8cd2b1b603a3afe9662ecf6c2ae63f4c298d66
$ docker logs dffb8401f8f88c2d1abf2e14ed8cd2b1b603a3afe9662ecf6c2ae63f4c298d66
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  bind: Cannot assign requested address
```

I tried:

1. checking if there's something running on the host on 7075/7076 (`lsof|grep -e 7075 -e 7076`)
2. IPv4: running the `docker run` with a `127.0.0.1` instead of `[::1]`
3. removing the portmapping command completely

all without a change in the error message, suspect is something in the docker image

**Steps to reproduce the issue:**
1. follow instructions [here](https://github.com/clemahieu/raiblocks/wiki/Docker-node) with current images on Ubuntu 16.04.3 LTS and docker version and kernel per spec

**Describe the results you received:**

Error above :-)

**Describe the results you expected:**

A running node :-)

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens every time

**Environment**:

- Ubuntu 16.04.3 LTS
- 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- The current one being pulled by instructions at [here](https://github.com/clemahieu/raiblocks/wiki/Docker-node)
- Docker version 17.12.0-ce, build c97c6d6

**logs**

No RaiBlocks logs, fails at docker startup

**Comment by cryptocode** [comment] 2018-01-15 18:43
Duplicate of https://github.com/clemahieu/raiblocks/issues/407

**Comment by liujackie** [comment] 2018-01-15 19:00
IPv6 is required to run a RaiBlocks node. 
Make sure your box has an IPv6 adapter and that you can ping an IPv6 address (try the command `ping6 ::1`). You also need to edit the config.json file to allow RPC after first starting the container, then restart the container. Perhaps you would find this guide useful. https://www.reddit.com/r/RaiBlocks/comments/7qfeq4/guide_spin_up_your_own_raiblocks_representative/

**Comment by bbozo** [comment] 2018-01-15 21:07
Thanks :-D IPv6 works for me, yet the docker doesn't work, will check on the new guide :-)

**Comment by PlasmaPower** [comment] 2018-01-15 23:45
No, the docker daemon runs as root regardless of what you run the docker CLI as. On some systems, your user is in the `docker` group, which means you don't need `sudo`. Regardless, root is not the problem here.

**Comment by bbozo** [comment] 2018-01-16 08:39
Cool, the instructions should be updated to reflect this. NOT doing things
as root is common sense, reduces the attack surface, should be the default.

**Comment by PlasmaPower** [comment] 2018-01-16 13:58
No, I'm saying there's no difference between running the CLI as root or not as root. Docker is being run as root irregardless. From the Arch Linux wiki:

> Warning: Anyone added to the docker group is root equivalent. More information [here](https://github.com/docker/docker/issues/9976) and [here](https://docs.docker.com/engine/security/security/).

As you can see, you aren't using sudo, but you're root equivalent anyway. Using `docker` essentially elevates you to root.

**Comment by orhanhenrik** [comment] 2018-01-19 12:33
You need to change the bind address in config.json as described in the wiki

**Comment by dsslimshaddy** [comment] 2018-01-26 20:33
same error docker starts then stops after a while giving that error changed the config.json too

**Comment by averissimo** [comment] 2018-03-08 02:20
What solved for me was to bind to ipv6 in docker command, specifically in the docker-compose.yml

- adding `enable_ipv6: true` and ipv6 subnet
- exposing ports  `7075:7075/tcp` `7075:7075/udp` and `::1:7076:7076/tcp`

This wiki command led me to the solution:  (from [Docker node](https://github.com/nanocurrency/raiblocks/wiki/Docker-node))

`sudo docker run -d -p 7075:7075/udp -p 7075:7075 -p [::1]:7076:7076 -v ~:/root nanocurrency/nano`

**Closed** 2018-05-13 13:56 UTC
