### ISSUE TITLE
Mouse stutters and pc slows down while using V13 classic wallet on windows

### ISSUE THREAD

**Issue by Nanoraii** [nanocurrency/raiblocks#868] opened 2018-05-14 13:03 UTC
Hello,

I think it's a rather old issure, but I wanted to bring it up again. Whenever I start the classic wallet on my Windows 10 laptop, the usability decreases masively. The mouse stutters from time to time and it is not possible to watch a simple Youtube video anymore because the audio stutters as well. I could understand it, if it was a very old laptop, but this is a brand new and pretty powerful one.
Here you can find a screenshot from my taskmanager with the wallet open:
https://imgur.com/a/mp16NBY

**Comment by cryptocode** [comment] 2018-05-14 13:04
Duplicate of https://github.com/nanocurrency/raiblocks/issues/227

**Comment by Nanoraii** [comment] 2018-05-14 13:09
Thanks for the reference. I thought it was addressed with v13, so I wanted to bring it up again.

**Comment by Nanoraii** [comment] 2018-05-14 14:29
Thanks for the answer.
Basically it doesn't matter. While it's synching it's worse but the problem is still there when the wallet is fully synched. Also I set io_threads to 2 now and while the CPU load is lower now the audio in a video still stutters from time to time.

**Comment by cryptocode** [comment] 2018-05-14 17:06
@Nanoraii Cinebench generates a completely different load than the node. The node uses a db which mmap's disk files, and which causes a large amount of hard pagefaults. Windows gets issues like audio drops when there's a flurry of pagefaults.

**Comment by Nanoraii** [comment] 2018-05-14 17:16
Thanks a lot for the explanation! I'm really a beginner in such things. Would it help to load the whole ledger into the RAM? Or is that not feasible?

**Comment by Nanoraii** [comment] 2018-05-20 19:40
I don't know if it's the April update of Windows or the transition to state blocks, but my problem seems to be gone. My laptop runs completely smooth now with the Nano wallet open.

**Closed** 2018-05-28 17:07 UTC
