### ISSUE TITLE
Display XRB Balance with a few decimal places

### ISSUE THREAD

**Issue by railocius** [nanocurrency/raiblocks#281] opened 2017-12-25 08:12 UTC
Currently, in rai_wallet v9.0 on the top it says "Balance (XRB): 2", but in reality if have 2.49 XRB.
The same for the account history, the amount in XRB is also only shown as integer number.

From a user-perspective it is imperative, that the balance amount is displayed with a few decimal places (e.g. default of 5 or 6). Otherwise, the user experiences anxiety over "lost, missing, or stolen" XRB.
I'm not sure, if rounded-towards-zero, rounded-towards-nearest, or truncated is the better way to display the balance. (You should not think you have more XRB, than you actually have, so rounding-towards-nearest (e.g. a rounding from 0.000016 rounding to . 0.00002 would mislead the user) should not be used).

The number of decimal places to show should be user-configurable in the settings.
The same behavior should be used, when switching from MRai to kRai. Obvisouly, not for raw xrb (=still an integer)

If a balance is non-zero, but due to truncating the significant digits it would be displayed as 0.0000, then there should be an added character, to indicate, that there is still some remaining XRB in that account. For example, you could display "Balance (XRB): 0.00000*", where the asterisk (*) means, that there is still some XRB in that account, but not displayed to the limited number of significant digits.

**Comment by railocius** [comment] 2017-12-25 08:18
Ups, same issue as #278 and #249

**Comment by rkeene** [comment] 2018-08-23 16:46
Duplicate of #249

**Closed by rkeene** 2018-08-23 16:46 UTC
