### ISSUE TITLE
Wallet doesn't show any decimal places for account balance

### ISSUE THREAD

**Issue by brockajones** [nanocurrency/raiblocks#278] opened 2017-12-25 03:50 UTC
I sent 0.1 Mxrb to my wallet and it says my current balance is 0. When I change the unit from Mxrb to Kxrb it shows the correct amount.

**Comment by paulmelis** [comment] 2017-12-27 23:03
It should also show the current unit for the balance, as showing just the number is asking for confusion. Btw, the Account viewer under Advanced has the same issue.

**Comment by rkeene** [comment] 2018-08-23 16:58
Duplicate of #249

**Closed by rkeene** 2018-08-23 16:58 UTC
