### ISSUE TITLE
Windows build fail

### ISSUE THREAD

**Issue by gaoxiangxyz** [nanocurrency/raiblocks#747] opened 2018-03-23 08:55 UTC
I follow build instruction to build raiblocks.
OS: Windows 7 64x
Visual Studio 2015
bootstrap_weights.cpp is included in the secure project.
It failed with below error message. 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "unsigned __int64 const rai_bootstrap_weights_size" (?rai_bootstrap_weights_size@@3_KB)	rai_node	E:\GitHub\raiblocks\build\node.lib(node.obj)	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "unsigned char const * const rai_bootstrap_weights" (?rai_bootstrap_weights@@3QBEB)	rai_node	E:\GitHub\raiblocks\build\node.lib(node.obj)	1	
```

**Comment by argakiig** [comment] 2018-03-23 16:11
extern arrays dont link properly for windows, here is a script to take the definition from bootstrap_weight.cpp into rai\node\node.cpp
```powershell
$size_t=select-string -path ".\bootstrap_weights.cpp" -Pattern "rai_bootstrap_weights_size"| foreach {$_.Line}
$old_size_t = "extern const size_t rai_bootstrap_weights_size;"
$char=select-string -path ".\bootstrap_weights.cpp" -Pattern "char rai_bootstrap_weights"| foreach {$_.Line}
$old_char = [regex]::Escape("extern const char rai_bootstrap_weights[];") 
select-string -path ".\rai\node\node.cpp" -Pattern $old_size_t -SimpleMatch | %{$curpath=$_.path; (get-content $curpath -Raw) -replace $old_char, $char| Out-File $curpath}
select-string -path ".\rai\node\node.cpp" -Pattern $old_size_t -SimpleMatch | %{$curpath=$_.path; (get-content $curpath -Raw) -replace $old_size_t, $size_t| Out-File $curpath}
```

Run this after cmake and then build

**Comment by rkeene** [comment] 2018-08-23 18:34
This issue appears to be resolved since there has been no feedback from the requester.  I'm going to close the issue, please re-open it if the issue is still on-going.

**Closed by rkeene** 2018-08-23 18:34 UTC
