### ISSUE TITLE
Update Repo description to point to nano.org

### ISSUE THREAD

**Issue by goldcaddy77** [nanocurrency/raiblocks#649] opened 2018-02-19 17:18 UTC
This repo's description is still pointing to raiblocks.net.  We should get all links that previously pointed there going to [nano.org](https://nano.org/) so that we build some SEO and get to the top of the Google search results.

<img width="437" alt="screen shot 2018-02-19 at 12 16 41 pm" src="https://user-images.githubusercontent.com/573625/36389880-cce4a9e6-156e-11e8-9c1b-5e1eed203bab.png">

**Comment by Stormtv** [comment] 2018-02-19 18:46
Duplicate of #627 but it will be done soon

**Closed** 2018-05-13 14:10 UTC
