### ISSUE TITLE
Windows Defender alerts on Rai 9 RC3 Windows download

### ISSUE THREAD

**Issue by AOEUPL-PHE** [nanocurrency/raiblocks#252] opened 2017-12-21 05:40 UTC
I downloaded https://github.com/clemahieu/raiblocks/releases/download/V9.0/rai-9.0.0-win64.exe on 12/20/17.

![chrome_2017-12-20_23-37-58](https://user-images.githubusercontent.com/24926512/34242030-006a4394-e5df-11e7-954d-196e23eec12a.png)

**Comment by clemahieu** [comment] 2017-12-21 05:58
Is your system up to date?  Are you running in to this? http://www.tomsguide.com/answers/id-3390537/trojan-false-positive.html

**Comment by AOEUPL-PHE** [comment] 2017-12-21 20:38
It's up to date.  

![applicationframehost_2017-12-21_14-36-41](https://user-images.githubusercontent.com/24926512/34274015-68993ee8-e65c-11e7-87a1-e6ae7e2d5281.png)

Downloading the installer and scanning it does not trigger anything.  However, launching the installer causes windows defender to set off an alert and it kills the installer.

I verified the hash was `E3EC99E4ADA4CE88D90A07D096B70F9AD3868D32C366B3850CA66B0A37D919F5`

**Comment by csleary** [comment] 2017-12-24 15:24
@AOEUPL-PHE Looks like you may have just posted an account seed. Please be careful.

I go the same trojan warning. I'm confident it's a false positive, but frankly when it comes to crypto, it's not worth the risk.

**Comment by AOEUPL-PHE** [comment] 2017-12-24 20:20
That's not an account seed, it's a hash of the exe which is used to verify that the exe was not tampered with.

**Comment by csleary** [comment] 2017-12-24 20:41
No worries; wasn't sure because of the capital letters, but I see it on the release page.

You *can* actually import it as an account though. 😄

**Comment by paul8046** [comment] 2017-12-25 04:04
I also get this error and can confirm that the steps listed to replicate the error are correct.

**Comment by rkeene** [comment] 2018-08-23 16:49
Duplicate of #45

**Closed by rkeene** 2018-08-23 16:49 UTC
