### ISSUE TITLE
More PoW

### ISSUE THREAD

**Issue by ghost** [nanocurrency/raiblocks#16] opened 2016-10-05 08:28 UTC
Make send/receive tx hash work harder, something like a 3-5x difficulty

**Comment by clemahieu** [comment] 2016-10-12 23:27
I would like to turn the difficulty up a bit, what's your concern with where it is?

Ideally I'd really like to find a better proof of work, something that takes polynomial time with a constant time verification instead of taking exponential time with a constant verification.  This would disincentivise parallel trial an error computation of work and computation speed scales slower than parallelism.

The closest idea I have right now is computing a discrete square root but I'm hoping for something better.

**Comment by mikerow** [comment] 2016-10-12 23:33
Hi, the idea of increase PoW was substained by:
- make deeper rollback harder
- a normal computer (definition of normal is a PC that you pay 500$) take about 40-60 seconds to perform a payment.

That's a guess, I'll do a little probe about the alternative you provided above.

**Comment by baundul** [comment] 2017-01-24 18:03
ok

**Comment by RaiBlocksDisciple** [comment] 2017-04-11 22:15
Another factor to consider is that a higher PoW difficulty can hinder adoption.

I'm not sure how computationally expensive handling thousands of hypothetical transactions would be right now (maybe it's relatively cheap?). 

For services like exchanges where thousands of transactions can occur in a minute, a higher PoW difficulty can lead to higher costs for the the service provider.

Striking the delicate balance between security and scalability is important.

**Comment by rkeene** [comment] 2018-08-23 17:50
I'm going to close this as a duplicate of #506.

We are unable to merge tickets in GitHub, so in order to track the issue of managing spam on the network we will manage just a single ticket for this issue.

**Closed by rkeene** 2018-08-23 17:50 UTC
