### ISSUE TITLE
Nano_wallet (Win) can't send fractional amount in non-English OS

### ISSUE THREAD

**Issue by justdmitry** [nanocurrency/raiblocks#858] opened 2018-05-10 14:49 UTC
**Description of bug:**

Nano_wallet 12.1 (Windows) can't send fractional amount in russian/cyrillic OS, shows "Bad amount number" text.

**Steps to reproduce the issue:**

1. Prerequisites: Windows 10, nano-wallet v12.1 (synchronized to network), account with at least 0.0001 nano
2. Change windows regional settings to Russia (decimal symbol comma `,` , digit grouping space ` `), restart 
3. Try to send "0.0001" or "0,0001" to any address

**Describe the results you received:**

Message "Bad amount value" after "Send" button clicked.

**Describe the results you expected:**

Send-block generated.

**Additional info:**

Problem in number parsing. If I type `1` in amount buttons says "Not enough balance", if I type `1.0001` buttons says "Bad amount value".

**Comment by cryptocode** [comment] 2018-05-10 15:02
@justdmitry The classic wallet doesn't support decimal amounts. Change the scale under Advanced.

**Comment by rkeene** [comment] 2018-08-23 19:09
Duplicate of #530

**Closed by rkeene** 2018-08-23 19:09 UTC
