### ISSUE TITLE
Fedora 26 - Unable to start rai_wallet

### ISSUE THREAD

**Issue by pjhavariotis** [nanocurrency/raiblocks#488] opened 2018-01-14 06:59 UTC
**Description of bug:**
I have downloaded the latest version rai-9.0.0-Linux.
I'm getting the following error:
`Illegal instruction (core dumped)`

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:
Kernel
`Linux fedorahost 4.14.11-200.fc26.x86_64 `
Node version
`v6.12.0`

**logs**

**Comment by fallerOfFalls** [comment] 2018-01-14 13:27
I'm having the same issue, running Debian 9

**Comment by lgvz** [comment] 2018-01-21 07:38
Same, on both `rai_wallet` and `rai_node`.
This is duplicate of #365.

**Closed** 2018-05-13 13:54 UTC

**Comment by LotfiKobrosly** [comment] 2018-08-16 09:39
Wtf? Issues referencing goes in a loop with no answer... check issues #365 #316 #398 and it is almost not the same issue, as the node here doesn't even start to crash: it says `Illegal instruction (core dumped)`
