### ISSUE TITLE
Nano Wallet v14.2 spikes CPU utilization to 100% and crashes on Windows 10, but not Windows 7

### ISSUE THREAD

**Issue by comeback** [nanocurrency/raiblocks#991] opened 2018-07-25 14:31 UTC
**Description of bug:**

Guys... why does Nano Wallet v14.2 and all previous versions spike on Windows 10 and use 50% - 100% of CPU resources?  This has been an ongoing issue since inception, how come no one can fix it?  Why can't Russel Waters or anyone on the team fix this.   On Windows 7, the CPU never breaches 10%.  @ColinLeMahieu 

Every single wallet does not run well on Windows 10.

I've installed every single wallet since Raiblocks.

They all f*cking suck and spike on Windows 10.  It's embarrassing.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

**logs**

**Comment by rkeene** [comment] 2018-08-28 15:51
Many performance improvements went into V15, from which the latest Desktop Wallet is based.  Can you try again with the latest version and see if things have improved ?

**Comment by zhyatt** [comment] 2018-12-27 18:07
Closing out as not able to reproduce after v15.

**Closed by zhyatt** 2018-12-27 18:07 UTC
Labels: bug, question
