### ISSUE TITLE
Windows Problem Reporting kicks in full gear after closing Node 10.01

### ISSUE THREAD

**Issue by sboppudiptg** [nanocurrency/raiblocks#659] opened 2018-02-21 15:50 UTC
**Description of bug:**

When Nano wallet 10.01 is closed even after full sync, Windows Problem Reporting service kicks in and is taking up 30% cpu. Happens consistently.

**Steps to reproduce the issue:**
1. Open nano wallet on Windows 10
2. Close it (synced or not doesn't matter)
3. Check in Task Manager.

**Describe the results you received:**
Windows Problem Reporting Service runs at 30% cpu every time. Had to reboot to stop it.

**Describe the results you expected:**
Clean close.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

Windows 10
Node 10.01

**logs**

[2018-02-21 07:44:45.097671]: Block D22F9E35F5C5ABA6217D75833854FEB9747B3ABD407B036DC4B482C10193F835 was republished to peers
[2018-02-21 07:44:49.197240]: Frontier sending finished
[2018-02-21 07:44:53.824135]: Node stopping
[2018-02-21 07:44:53.860177]: UDP Receive error: The I/O operation has been aborted because of either a thread exit or an application request
[2018-02-21 07:44:53.866655]: Error while accepting bootstrap connections: The I/O operation has been aborted because of either a thread exit or an application request

**Comment by cryptocode** [comment] 2018-02-21 17:37
Duplicate of https://github.com/nanocurrency/raiblocks/issues/635

**Comment by argakiig** [comment] 2018-04-02 14:59
Closed as duplicate of #635

**Closed by argakiig** 2018-04-02 14:59 UTC
