### ISSUE TITLE
RPC - accounts_pending return invalid json when account does not have pending transactions

### ISSUE THREAD

**Issue by rotilho** [nanocurrency/raiblocks#896] opened 2018-05-28 19:40 UTC
When using account_pending action the node returns invalid json (empty string instead of empty map)

Request: `{"accounts":["xrb_3534c73cym6pbb9nr6f1waqc3ta98o1nfbupy4w74h9xzp5zi3mbturb3ujn"],"threshold":"1","count":"9223372036854775807","action":"accounts_pending"}`

Response: `{"blocks":{"xrb_3534c73cym6pbb9nr6f1waqc3ta98o1nfbupy4w74h9xzp5zi3mbturb3ujn":""}}`

Correct response `{"blocks":{"xrb_3534c73cym6pbb9nr6f1waqc3ta98o1nfbupy4w74h9xzp5zi3mbturb3ujn":"{}"}}`

**Comment by PlasmaPower** [comment] 2018-05-28 19:57
Duplicate of #499. This is a problem with the boost JSON library we're currently using.

**Closed by PlasmaPower** 2018-05-28 19:57 UTC
