### ISSUE TITLE
Strip whitespace in account entry boxes

### ISSUE THREAD

**Issue by paulmelis** [nanocurrency/raiblocks#317] opened 2017-12-28 20:43 UTC
In the desktop wallet copy-pasting an account ID in, for example, the `Change representative` entry box reports "Invalid account" when a single space follows the ID. Stripping the entered text of whitespace would be a nice UX improvement.

**Comment by rkeene** [comment] 2018-08-23 17:07
Closing this as a duplicate of #320

**Closed by rkeene** 2018-08-23 17:07 UTC
