### ISSUE TITLE
(Windows) Locks up PC for 100ms every 5 seconds

### ISSUE THREAD

**Issue by JeroenvdV** [nanocurrency/raiblocks#314] opened 2017-12-28 17:04 UTC
Whenever the wallet is open, there is this regularly recurring lockup that happens every few seconds during which my cursor doesn't move and spotify skips a bit. This isn't solved by lowering the process' priority in task manager.

**Comment by dannyvankooten** [comment] 2017-12-28 18:10
This is a possible duplicate of #268 and #227

**Comment by Jaxkr** [comment] 2017-12-31 08:49
I also have this issue. Audio and cursor problems when using the wallet. It makes my computer nearly unusable, and by extension the wallet is unusuable.

**Comment by rkeene** [comment] 2018-08-23 17:07
There is ongoing work to improve this situation as part of node stratification #1092 

I'm going to close this issue so we can track the improvement more centrally.

**Closed by rkeene** 2018-08-23 17:07 UTC
