### ISSUE TITLE
Latest master: Some blocks are never sent to RPC callback, causing holes in history

### ISSUE THREAD

**Issue by eirikrye** [nanocurrency/raiblocks#835] opened 2018-04-28 12:44 UTC
It may be related to commit 8131a608f9cead9353a007d60aaaf603d2d7bb1e.

For example, I got a callback for block hash `054B5C310C465647B2B078D5BAB440855F344ED4CEB15F8CF12E897231415D01`, and then `68A76178D4CC8BB71441B7759E743365D036CD0952F9C4D3FDD37F183421B313`.

I never got the callback for block hash `866344260CEE242F8FE9C8060B260923E1B1146F6D31D50EAC421A1AF6786665`.

Looking at one of the active chains (the Binance rep), I would say this happens quite frequently, roughly every 30-50  blocks.

**Comment by eirikrye** [comment] 2018-04-28 12:52
Closing pending further investigation.

**Comment by meltingice** [comment] 2018-05-02 15:40
I can confirm that I am in fact missing a fair number of callback requests for blocks. Looking at the [Binance transaction history](https://nano.meltingice.net/explorer/account/xrb_3jwrszth46rk1mu7rmb4rhm54us8yg1gw3ipodftqtikf5yqdyr7471nsg1k) there are a _lot_ of missing timestamps. I don't have any reason to believe that this is due to some kind of system failure on my end as the system has been running continuously without issue.

**Comment by clemahieu** [comment] 2018-05-02 15:41
One thing that would help would be if someone could put in a PR to keep both the RPC and callback HTTP connections open instead of closing them.  I can get to it eventually but if someone can write it up we could get it in faster.

**Comment by eirikrye** [comment] 2018-05-02 15:45
I'm also observing this issue in the 12.1 release build, albeit much less frequently. Some blocks simply never hit the RPC for some reason.

**Comment by baryluk** [comment] 2018-05-30 19:58
I would suggest to use proper queuing / pubsub solution like ZeroMQ, or some Go equivalent. HTTP callback is externally poor method of doing things, without proper flow control, rate limiting, loadbalancing across multiple endpoints, doing retries, buffering in permanent storage if the callback endpoint is not available, etc.

**Comment by rkeene** [comment] 2018-08-30 16:43
We are working on addressing by enabling a pluggable system to supplant the callback system (issue #1096).  One of the plugins will be the current callback system, so no functionality will change but there will be more options for ensuring blocks get sent into other systems.

**Comment by rkeene** [comment] 2018-08-30 16:50
I am going to close this ticket so we can track fixing the more specific items:

- Pluggable system that can be integrated directly without HTTP servers being involved (#1096)
- Improving the callback HTTP client to support HTTP keep-live (#1120)

Please let me know if you have any questions !

**Closed by rkeene** 2018-08-30 16:50 UTC
