### ISSUE TITLE
Issue Didn't solved #1505

### ISSUE THREAD

**Issue by prateektiwari7** [nanocurrency/raiblocks#1520] opened 2018-12-31 09:58 UTC
Hi @argakiig 

I think you didn't answer that, dont make this in the loop. I check the issue there in #1519 which make me again redirect to #1505.

Please solve the issue atleast at one position

_Originally posted by @prateektiwari7 in https://github.com/nanocurrency/raiblocks/issues/1505#issuecomment-450627105_

**Comment by prateektiwari7** [comment] 2018-12-31 10:21
@argakiig 

I already posted this issue in #1505 and #1519. But I think you make them in loop without solving them.

Can you please check the issue #1505 and solve it .


Thanks @argakiig

**Comment by zhyatt** [comment] 2018-12-31 11:34
@prateektiwari7 Also closing this as a duplicate of #1505. We will be looking at your issue through ticket #1505, please look for updates there instead of creating new tickets.

**Closed by zhyatt** 2018-12-31 11:34 UTC

**Comment by prateektiwari7** [comment] 2018-12-31 11:43
Hi @zhyatt 

Thanks for sharing the message. I am looking for feedback now on #1505.
