### ISSUE TITLE
[Feature Request] Allow sending fractional amounts of XRB via the wallet.

### ISSUE THREAD

**Issue by FSMaxB** [nanocurrency/raiblocks#530] opened 2018-01-23 13:51 UTC
**Description of bug:**
I can't send fractional amounts of RaiBlocks. If I try to send it, it shows the error message. "Bad amount number".

**Steps to reproduce the issue:**
1. Open the GUI wallet.
2. Click "send"
3. Type in "0.01" or "0,01" into "Amount" field and click send.

**Describe the results you received:**
The "Send" button changes it's text to "Bad amount number".

**Describe the results you expected:**
It should send the money without any errors.

**Additional information you deem important (e.g. issue happens only occasionally):**
I think this might be related to the system language and locale. This is kind of hairy in C and C++ because some languages (like German) use a `,` as the decimal separator instead of a `.`. But I'm not really sure, especially because the problem still persisted after changing the lanugage and locale to `en_US.UTF-8` via `env -i` (meaning a fresh environment).

**Environment**:
* Environment variables
  - `LANG=de_DE.UTF-8`
  - `LC_MEASUREMENT=de_DE.UTF-8`
  - `LC_PAPER=de_DE.UTF-8`
  - `LC_MONETARY=de_DE.UTF-8`
  - `LC_NUMERIC=de_DE.UTF-8`
  - `LC_TIME=de_DE.UTF-8`
* OS: Archlinux with linux 4.14.14-1-hardened, x86_64
* Node version 9.0 (commit f70efdc7)

**logs**
Nothing related to the problem shows up in the logs.

**Comment by FSMaxB** [comment] 2018-01-23 13:52
Note: To reproduce I don't even have to input a receiver address, so you should be able to reproduce the issue without actually sending any money anywhere.

**Comment by cryptocode** [comment] 2018-01-23 14:12
@FSMaxB For now, change the scale

**Comment by FSMaxB** [comment] 2018-01-23 14:18
@cryptocode Yes, that works. Is that a bug or a problem in the design?

**Comment by FSMaxB** [comment] 2018-01-23 14:26
https://github.com/clemahieu/raiblocks/blob/655fa66609f82d415f4a7e1424323bc1c49abc18/rai/lib/numbers.cpp#L295-L318

Makes sense that it doesn't work. This only parses integers. Although I don't quite understand where `operator>>` for `rai::uint256_union` comes from.

**Comment by cryptocode** [comment] 2018-01-23 14:33
> Yes, that works. Is that a bug or a problem in the design?

Just not implemented in this wallet. Use the scales.

**Comment by FSMaxB** [comment] 2018-01-23 14:44
So then this issue is now a feature request for the wallet to support sending fractional values.

**Comment by rkeene** [comment] 2018-08-23 17:54
This ticket is a duplicate of #249.

I'm going to close this ticket so we can track that single issue.

**Closed by rkeene** 2018-08-23 17:54 UTC
