### ISSUE TITLE
rai_wallet 9.0 is interfering with my music (foobar2000)

### ISSUE THREAD

**Issue by Kokkomaki** [nanocurrency/raiblocks#268] opened 2017-12-23 12:12 UTC
The music lags for 0.1-0.5 seconds but then continues normally. This happens from time to time during listening. I closed rai_wallet and then it stopped. Not a big issue, but weird still. It is noticeable though.

**Comment by pocesar** [comment] 2017-12-23 13:04
same as #227

**Comment by MtKokko** [comment] 2017-12-23 13:06
Ooo, nice to know I am not alone! Thanks for letting me know.

**Comment by citizen2077** [comment] 2017-12-23 13:07
Yes I have updated to version 9.0 release and am still getting audio buzzed every 30 seconds - minute during wallet syncing at least. No apps open in tray, just running Windows 10 64bit, audio playing through chrome -> youtube

**Comment by Dekoze** [comment] 2017-12-24 06:10
Open config.json at:

**Comment by rkeene** [comment] 2018-08-23 16:55
Duplicate of #227

**Closed by rkeene** 2018-08-23 16:55 UTC
