### ISSUE TITLE
Exception while running wallet: bind: Address already in use

### ISSUE THREAD

**Issue by KennyKormik** [nanocurrency/raiblocks#355] opened 2018-01-01 09:23 UTC
After successful updating Raiblocks Desktop application from V8.0 to V9.0 on the Mac. 
I get this message after closing the app and restarting it:

Exception while running wallet: bind: Address already in use

The only thing helps is restarting the whole OS and the app works like a charm again.

**Comment by Dekoze** [comment] 2018-01-02 00:42
Next time this happens can you open terminal and type `netstat -atu` and paste the output here?

**Comment by sawmurai** [comment] 2018-01-02 14:35
Related question: Why is the node launching a server if RPC is not enabled? Or put differently: Can launching the server be made optional?

**Comment by KennyKormik** [comment] 2018-01-03 08:31
Active LOCAL (UNIX) domain sockets
Address          Type   Recv-Q Send-Q            Inode             Conn             Refs          Nextref Addr
358a54f66439fa53 stream      0      0                0 358a54f6643a0ea3                0                0 /var/folders/36/wshlv8gs57q5sjxt7n4qzcmh0000gn/T/iTerm2-temp-socket.a383jf
358a54f6643a0ea3 stream      0      0                0 358a54f66439fa53                0                0
358a54f66439fbe3 stream      0      0                0 358a54f66439fcab                0                0 /var/run/mDNSResponder
358a54f66439fcab stream      0      0                0 358a54f66439fbe3                0                0
358a54f658b2573b stream      0      0                0 358a54f658b23fcb                0                0 /var/run/mDNSResponder
358a54f658b23fcb stream      0      0                0 358a54f658b2573b                0                0
358a54f658b25e43 stream      0      0                0 358a54f658b242eb                0                0 /var/run/mDNSResponder
358a54f658b242eb stream      0      0                0 358a54f658b25e43                0                0
358a54f658b25b23 stream      0      0                0 358a54f658b23b1b                0                0 /var/run/mDNSResponder
358a54f658b23b1b stream      0      0                0 358a54f658b25b23                0                0
358a54f65546f47b stream      0      0                0 358a54f6554704e3                0                0 /var/run/mDNSResponder
358a54f6554704e3 stream      0      0                0 358a54f65546f47b                0                0
358a54f6643a1a5b stream      0      0                0 358a54f6643a173b                0                0 /var/run/mDNSResponder
358a54f6643a173b stream      0      0                0 358a54f6643a1a5b                0                0
358a54f6643a0d13 stream      0      0                0 358a54f66439f413                0                0 /var/run/mDNSResponder
358a54f66439f413 stream      0      0                0 358a54f6643a0d13                0                0
358a54f6643a092b stream      0      0 358a54f651ba43db                0                0                0 /tmp/91a035b35f3157da8873b4ed1a02e2e0-{87A94AB0-E370-4cde-98D3-ACC110C5967D}
358a54f66439f8c3 stream      0      0                0 358a54f6643a15ab                0                0 /var/run/mDNSResponder
358a54f6643a15ab stream      0      0                0 358a54f66439f8c3                0                0
358a54f6643a1cb3 stream      0      0                0 358a54f66439f66b                0                0 /var/run/mDNSResponder
358a54f66439f66b stream      0      0                0 358a54f6643a1cb3                0                0
358a54f66439f0f3 stream      0      0                0 358a54f6643a1fd3                0                0 /var/run/mDNSResponder
358a54f6643a1fd3 stream      0      0                0 358a54f66439f0f3                0                0
358a54f66439ff03 stream      0      0                0 358a54f6643a0c4b                0                0 /var/run/mDNSResponder
358a54f6643a0c4b stream      0      0                0 358a54f66439ff03                0                0
358a54f65317e41b stream      0      0 358a54f65f9da92b                0                0                0 /var/folders/36/wshlv8gs57q5sjxt7n4qzcmh0000gn/T/discord-ipc-0
358a54f65317efd3 stream      0      0                0 358a54f65317d543                0                0
358a54f65317d543 stream      0      0                0 358a54f65317efd3                0                0
358a54f65317ef0b stream      0      0                0 358a54f65317ce3b                0                0
358a54f65317ce3b stream      0      0                0 358a54f65317ef0b                0                0
358a54f65317ee43 stream      0      0                0 358a54f65317e803                0                0 /var/run/mDNSResponder
358a54f65317e803 stream      0      0                0 358a54f65317ee43                0                0
358a54f65317c98b stream      0      0 358a54f64c1194d3                0                0                0 /var/folders/36/wshlv8gs57q5sjxt7n4qzcmh0000gn/T/discord.sock
358a54f65317c733 stream      0      0                0 358a54f65317e5ab                0                0
358a54f65317e5ab stream      0      0                0 358a54f65317c733                0                0
358a54f658b238c3 stream      0      0                0                0                0                0
358a54f658b25d7b stream      0      0                0 358a54f658b25cb3                0                0 /var/run/mDNSResponder
358a54f658b25cb3 stream      0      0                0 358a54f658b25d7b                0                0
358a54f658b23be3 stream      0      0                0 358a54f658b23cab                0                0 /var/run/mDNSResponder
358a54f658b23cab stream      0      0                0 358a54f658b23be3                0                0
358a54f658b254e3 stream      0      0                0 358a54f658b2447b                0                0 /var/run/mDNSResponder
358a54f658b2447b stream      0      0                0 358a54f658b254e3                0                0
358a54f658b2528b stream      0      0                0 358a54f658b24543                0                0 /var/run/mDNSResponder
358a54f658b24543 stream      0      0                0 358a54f658b2528b                0                0
358a54f658b2460b stream      0      0                0 358a54f658b24ea3                0                0
358a54f658b24ea3 stream      0      0                0 358a54f658b2460b                0                0
358a54f658b246d3 stream      0      0                0 358a54f658b2479b                0                0
358a54f658b2479b stream      0      0                0 358a54f658b246d3                0                0
358a54f658b24ddb stream      0      0                0 358a54f658b24863                0                0
358a54f658b24863 stream      0      0                0 358a54f658b24ddb                0                0
358a54f658b249f3 stream      0      0                0 358a54f658b24c4b                0                0 /var/run/mDNSResponder
358a54f658b24c4b stream      0      0                0 358a54f658b249f3                0                0
358a54f658b24b83 stream      0      0 358a54f658b1c73b                0                0                0 /var/folders/36/wshlv8gs57q5sjxt7n4qzcmh0000gn/T/chrome-cthUPg/Socket
358a54f658b24abb stream      0      0 358a54f658b1c54b                0                0                0 /var/folders/36/wshlv8gs57q5sjxt7n4qzcmh0000gn/T/.io.nwjs.nw.FYlNwK/SingletonSocket
358a54f65546e413 stream      0      0                0 358a54f65546e34b                0                0
358a54f65546e34b stream      0      0                0 358a54f65546e413                0                0
358a54f65546e1bb stream      0      0                0 358a54f655470beb                0                0
358a54f655470beb stream      0      0                0 358a54f65546e1bb                0                0
358a54f64e2361bb stream      0      0                0 358a54f64e238fd3                0                0
358a54f64e238fd3 stream      0      0                0 358a54f64e2361bb                0                0
358a54f65546e0f3 stream      0      0                0 358a54f655470cb3                0                0
358a54f655470cb3 stream      0      0                0 358a54f65546e0f3                0                0
358a54f65546e283 stream      0      0                0 358a54f655470b23                0                0 /var/run/mDNSResponder
358a54f655470b23 stream      0      0                0 358a54f65546e283                0                0
358a54f65546e733 stream      0      0                0 358a54f65546e66b                0                0 /var/run/mDNSResponder
358a54f65546e66b stream      0      0                0 358a54f65546e733                0                0
358a54f65546ebe3 stream      0      0                0 358a54f65546ecab                0                0 /var/run/mDNSResponder
358a54f65546ecab stream      0      0                0 358a54f65546ebe3                0                0
358a54f65546ed73 stream      0      0                0 358a54f65546ee3b                0                0 /var/run/mDNSResponder
358a54f65546ee3b stream      0      0                0 358a54f65546ed73                0                0
358a54f65546ef03 stream      0      0                0 358a54f655470353                0                0 /var/run/mDNSResponder
358a54f655470353 stream      0      0                0 358a54f65546ef03                0                0
358a54f65547028b stream      0      0                0 358a54f6554701c3                0                0 /var/run/mDNSResponder
358a54f6554701c3 stream      0      0                0 358a54f65547028b                0                0
358a54f65546efcb stream      0      0                0 358a54f655470033                0                0 /var/run/mDNSResponder
358a54f65546f093 stream      0      0                0 358a54f65546ff6b                0                0 /var/run/mDNSResponder
358a54f6554700fb stream      0      0                0 358a54f65546fabb                0                0 /var/run/mDNSResponder
358a54f655470033 stream      0      0                0 358a54f65546efcb                0                0
358a54f65546f15b stream      0      0                0 358a54f65546fea3                0                0 /var/run/mDNSResponder
358a54f65546f223 stream      0      0                0 358a54f65546fc4b                0                0 /var/run/mDNSResponder
358a54f65546ff6b stream      0      0                0 358a54f65546f093                0                0
358a54f65546fea3 stream      0      0                0 358a54f65546f15b                0                0
358a54f65546fc4b stream      0      0                0 358a54f65546f223                0                0
358a54f65546fabb stream      0      0                0 358a54f6554700fb                0                0
358a54f65546f3b3 stream      0      0                0 358a54f65546f2eb                0                0 /var/run/mDNSResponder
358a54f65546f2eb stream      0      0                0 358a54f65546f3b3                0                0
358a54f65317ed7b stream      0      0                0 358a54f65317ecb3                0                0
358a54f65317ecb3 stream      0      0                0 358a54f65317ed7b                0                0
358a54f65317ebeb stream      0      0                0 358a54f65317eb23                0                0
358a54f65317eb23 stream      0      0                0 358a54f65317ebeb                0                0
358a54f65317ea5b stream      0      0                0 358a54f65317e993                0                0
358a54f65317e993 stream      0      0                0 358a54f65317ea5b                0                0
358a54f65317c413 stream      0      0                0 358a54f65317c34b                0                0
358a54f65317c34b stream      0      0                0 358a54f65317c413                0                0
358a54f65317e8cb stream      0      0                0 358a54f65317c4db                0                0 /var/run/mDNSResponder
358a54f65317c4db stream      0      0                0 358a54f65317e8cb                0                0
358a54f65317c7fb stream      0      0                0 358a54f65317e353                0                0 /var/run/mDNSResponder
358a54f65317e353 stream      0      0                0 358a54f65317c7fb                0                0
358a54f65317e1c3 stream      0      0                0 358a54f65317e0fb                0                0 /var/run/mDNSResponder
358a54f65317e0fb stream      0      0                0 358a54f65317e1c3                0                0
358a54f65317cfcb stream      0      0                0 358a54f65317d15b                0                0 /var/run/mDNSResponder
358a54f65317d093 stream      0      0                0 358a54f65317e033                0                0 /var/run/mDNSResponder
358a54f65317d15b stream      0      0                0 358a54f65317cfcb                0                0
358a54f65317e033 stream      0      0                0 358a54f65317d093                0                0
358a54f65317df6b stream      0      0                0 358a54f65317dea3                0                0 /var/run/mDNSResponder
358a54f65317dea3 stream      0      0                0 358a54f65317df6b                0                0
358a54f65317dd13 stream      0      0                0 358a54f65317dc4b                0                0 /var/run/mDNSResponder
358a54f65317dc4b stream      0      0                0 358a54f65317dd13                0                0
358a54f65317d60b stream      0      0                0 358a54f65317d92b                0                0 /var/run/mDNSResponder
358a54f65317d92b stream      0      0                0 358a54f65317d60b                0                0
358a54f64e238b23 stream      0      0 358a54f652ca1d8b                0                0                0 /var/tmp/filesystemui.socket
358a54f64e238a5b stream      0      0 358a54f652ca2453                0                0                0 /private/tmp/com.apple.launchd.wMpNpJLOM1/Render
358a54f64e238993 stream      0      0 358a54f652ca2263                0                0                0 /private/tmp/com.apple.launchd.FHjs9HodLl/Listeners
358a54f64e236283 stream      0      0                0 358a54f64e236413                0                0 /var/run/mDNSResponder
358a54f64e236413 stream      0      0                0 358a54f64e236283                0                0
358a54f64e238033 stream      0      0 358a54f6500d04d3                0                0                0 /var/run/displaypolicyd/state
358a54f64e236a53 stream      0      0                0 358a54f64e23828b                0                0
358a54f64e23828b stream      0      0                0 358a54f64e236a53                0                0
358a54f64e236d73 stream      0      0 358a54f64f208b1b                0                0                0 /var/run/pppconfd
358a54f64e236f03 stream      0      0 358a54f64e51054b                0                0                0 /var/run/com.macpaw.CleanMyMac3.Agent.socket
358a54f64e237d13 stream      0      0 358a54f64e510263                0                0                0 /var/run/com.macpaw.CleanMyMac2.Agent.socket
358a54f64e237c4b stream      0      0 358a54f64e4dd643                0                0                0 /var/rpc/ncalrpc/srvsvc
358a54f64e236fcb stream      0      0 358a54f64e4dd54b                0                0                0 /var/rpc/ncacn_np/srvsvc
358a54f64e237b83 stream      0      0 358a54f64e4cff7b                0                0                0 /var/run/usbmuxd
358a54f64e237abb stream      0      0 358a54f64e4d0833                0                0                0 /var/rpc/ncalrpc/wkssvc
358a54f64e237093 stream      0      0 358a54f64e4d0453                0                0                0 /var/rpc/ncacn_np/wkssvc
358a54f64e23715b stream      0      0 358a54f64e4c73db                0                0                0 /var/rpc/ncacn_np/mdssvc
358a54f64e2379f3 stream      0      0 358a54f64e4c8a23                0                0                0 /var/rpc/ncalrpc/lsarpc
358a54f64e23792b stream      0      0 358a54f64e4c79ab                0                0                0 /var/rpc/ncacn_np/lsarpc
358a54f64e237863 stream      0      0 358a54f64e470ff3                0                0                0 /var/run/mDNSResponder
358a54f64e237223 stream      0      0 358a54f64e470643                0                0                0 /var/run/systemkeychaincheck.socket
358a54f64e23779b stream      0      0 358a54f64e4617bb                0                0                0 /private/var/run/.sim_diagnosticd_socket
358a54f64e2376d3 stream      0      0 358a54f64e459833                0                0                0 /var/run/portmap.socket
358a54f64e23760b stream      0      0 358a54f64e45073b                0                0                0 /var/run/vpncontrol.sock
358a54f64e2372eb stream      0      0 358a54f64e43516b                0                0                0 /var/rpc/ncalrpc/NETLOGON
358a54f64e2373b3 stream      0      0 358a54f64e40fd0b                0                0                0 /private/var/run/cupsd
358a54f6643a1673 dgram       0      0                0 358a54f64e237543                0 358a54f66439f733
358a54f66439f733 dgram       0      0                0 358a54f64e237543                0 358a54f66439f98b
358a54f65546fd13 dgram       0      0                0 358a54f65546ea53 358a54f65546ea53                0
358a54f65546ea53 dgram       0      0                0 358a54f65546fd13 358a54f65546fd13                0
358a54f6643a1f0b dgram       0      0                0 358a54f6643a079b 358a54f6643a079b                0
358a54f6643a079b dgram       0      0                0 358a54f6643a1f0b 358a54f6643a1f0b                0
358a54f66439f98b dgram       0      0                0 358a54f64e237543                0 358a54f6643a1beb
358a54f6643a1beb dgram       0      0                0 358a54f64e237543                0 358a54f66439fb1b
358a54f66439fb1b dgram       0      0                0 358a54f64e237543                0 358a54f65546f60b
358a54f6643a1e43 dgram       0      0                0 358a54f6643a1d7b 358a54f6643a1d7b                0
358a54f6643a1d7b dgram       0      0                0 358a54f6643a1e43 358a54f6643a1e43                0
358a54f65546f60b dgram       0      0                0 358a54f64e237543                0 358a54f658b25a5b
358a54f658b25a5b dgram       0      0                0 358a54f64e237543                0 358a54f658b23733
358a54f658b2366b dgram       0      0                0 358a54f658b23a53 358a54f658b23a53                0
358a54f658b23a53 dgram       0      0                0 358a54f658b2366b 358a54f658b2366b                0
358a54f658b23733 dgram       0      0                0 358a54f64e237543                0 358a54f658b237fb
358a54f658b237fb dgram       0      0                0 358a54f64e237543                0 358a54f658b23283
358a54f658b23283 dgram       0      0                0 358a54f64e237543                0 358a54f65317c283
358a54f658b243b3 dgram       0      0                0 358a54f658b23413 358a54f658b23413                0
358a54f658b23413 dgram       0      0                0 358a54f658b243b3 358a54f658b243b3                0
358a54f65317c283 dgram       0      0                0 358a54f64e237543                0 358a54f655470803
358a54f655470803 dgram       0      0                0 358a54f64e237543                0 358a54f658b25993
358a54f658b23d73 dgram       0      0                0 358a54f658b25673 358a54f658b25673                0
358a54f658b25673 dgram       0      0                0 358a54f658b23d73 358a54f658b23d73                0
358a54f658b25993 dgram       0      0                0 358a54f64e237543                0 358a54f658b24093
358a54f658b24093 dgram       0      0                0 358a54f64e237543                0 358a54f658b258cb
358a54f658b258cb dgram       0      0                0 358a54f64e237543                0 358a54f658b2541b
358a54f658b2541b dgram       0      0                0 358a54f64e237543                0 358a54f658b25353
358a54f658b251c3 dgram       0      0                0 358a54f658b25033 358a54f658b25033                0
358a54f658b25033 dgram       0      0                0 358a54f658b251c3 358a54f658b251c3                0
358a54f658b25353 dgram       0      0                0 358a54f64e237543                0 358a54f658b250fb
358a54f658b250fb dgram       0      0                0 358a54f64e237543                0 358a54f658b24f6b
358a54f658b24f6b dgram       0      0                0 358a54f64e237543                0 358a54f65317d47b
358a54f658b24d13 dgram       0      0                0 358a54f658b2492b 358a54f658b2492b                0
358a54f658b2492b dgram       0      0                0 358a54f658b24d13 358a54f658b24d13                0
358a54f65317d47b dgram       0      0                0 358a54f64e237543                0 358a54f65317e73b
358a54f655470fd3 dgram       0      0                0 358a54f655470f0b 358a54f655470f0b                0
358a54f655470f0b dgram       0      0                0 358a54f655470fd3 358a54f655470fd3                0
358a54f65317e73b dgram       0      0                0 358a54f64e237543                0 358a54f65546e4db
358a54f65546e4db dgram       0      0                0 358a54f64e237543                0 358a54f6554708cb
358a54f655470a5b dgram       0      0                0 358a54f65546e5a3 358a54f65546e5a3                0
358a54f65546e5a3 dgram       0      0                0 358a54f655470a5b 358a54f655470a5b                0
358a54f6554708cb dgram       0      0                0 358a54f64e237543                0 358a54f655470993
358a54f655470993 dgram       0      0                0 358a54f64e237543                0 358a54f65546f79b
358a54f6554705ab dgram       0      0                0 358a54f65546f6d3 358a54f65546f6d3                0
358a54f65546f6d3 dgram       0      0                0 358a54f6554705ab 358a54f6554705ab                0
358a54f65546f79b dgram       0      0                0 358a54f64e237543                0 358a54f65317c8c3
358a54f65546f92b dgram       0      0                0 358a54f65546f9f3 358a54f65546f9f3                0
358a54f65546f9f3 dgram       0      0                0 358a54f65546f92b 358a54f65546f92b                0
358a54f65546fb83 dgram       0      0                0 358a54f65546f863 358a54f65546f863                0
358a54f65546f863 dgram       0      0                0 358a54f65546fb83 358a54f65546fb83                0
358a54f65317c5a3 dgram       0      0                0 358a54f65317c66b 358a54f65317c66b                0
358a54f65317c66b dgram       0      0                0 358a54f65317c5a3 358a54f65317c5a3                0
358a54f65317c8c3 dgram       0      0                0 358a54f64e237543                0 358a54f65317cb1b
358a54f65317cb1b dgram       0      0                0 358a54f64e237543                0 358a54f65317d6d3
358a54f65317d6d3 dgram       0      0                0 358a54f64e237543                0 358a54f65317e4e3
358a54f65317e4e3 dgram       0      0                0 358a54f64e237543                0 358a54f65317e28b
358a54f65317e28b dgram       0      0                0 358a54f64e237543                0 358a54f65317ccab
358a54f65317ccab dgram       0      0                0 358a54f64e237543                0 358a54f65317d3b3
358a54f65317d223 dgram       0      0                0 358a54f65317d2eb 358a54f65317d2eb                0
358a54f65317d2eb dgram       0      0                0 358a54f65317d223 358a54f65317d223                0
358a54f65317d3b3 dgram       0      0                0 358a54f64e237543                0 358a54f65317d79b
358a54f65317d79b dgram       0      0                0 358a54f64e237543                0 358a54f65317d863
358a54f65317d863 dgram       0      0                0 358a54f64e237543                0 358a54f65317d9f3
358a54f65317db83 dgram       0      0                0 358a54f65317dabb 358a54f65317dabb                0
358a54f65317dabb dgram       0      0                0 358a54f65317db83 358a54f65317db83                0
358a54f65317d9f3 dgram       0      0                0 358a54f64e237543                0 358a54f64e238beb
358a54f64e238beb dgram       0      0                0 358a54f64e237543                0 358a54f64e238803
358a54f64e238803 dgram       0      0                0 358a54f64e237543                0 358a54f64e23634b
358a54f64e23634b dgram       0      0                0 358a54f64e237543                0 358a54f64e2365a3
358a54f64e2365a3 dgram       0      0                0 358a54f64e237543                0 358a54f64e23873b
358a54f64e23873b dgram       0      0                0 358a54f64e237543                0 358a54f64e2384e3
358a54f64e23666b dgram       0      0                0 358a54f64e23841b 358a54f64e23841b                0
358a54f64e23841b dgram       0      0                0 358a54f64e23666b 358a54f64e23666b                0
358a54f64e2385ab dgram       0      0                0 358a54f64e236733 358a54f64e236733                0
358a54f64e236733 dgram       0      0                0 358a54f64e2385ab 358a54f64e2385ab                0
358a54f64e2384e3 dgram       0      0                0 358a54f64e237543                0 358a54f64e236b1b
358a54f64e2381c3 dgram       0      0                0 358a54f64e238353 358a54f64e238353                0
358a54f64e238353 dgram       0      0                0 358a54f64e2381c3 358a54f64e2381c3                0
358a54f64e2367fb dgram       0      0                0 358a54f64e2368c3 358a54f64e2368c3                0
358a54f64e2368c3 dgram       0      0                0 358a54f64e2367fb 358a54f64e2367fb                0
358a54f64e2380fb dgram       0      0                0 358a54f64e23698b 358a54f64e23698b                0
358a54f64e23698b dgram       0      0                0 358a54f64e2380fb 358a54f64e2380fb                0
358a54f64e236b1b dgram       0      0                0 358a54f64e237543                0 358a54f64e237f6b
358a54f64e236be3 dgram       0      0                0 358a54f64e236cab 358a54f64e236cab                0
358a54f64e236cab dgram       0      0                0 358a54f64e236be3 358a54f64e236be3                0
358a54f64e237f6b dgram       0      0                0 358a54f64e237543                0 358a54f64e236e3b
358a54f64e236e3b dgram       0      0                0 358a54f64e237543                0 358a54f64e23747b
358a54f64e237ea3 dgram       0      0                0 358a54f64e237ddb 358a54f64e237ddb                0
358a54f64e237ddb dgram       0      0                0 358a54f64e237ea3 358a54f64e237ea3                0
358a54f64e23747b dgram       0      0                0 358a54f64e237543                0                0
358a54f64e237543 dgram       0      0 358a54f64e21f92b                0 358a54f6643a1673                0 /private//var/run/syslog

**Comment by lalanza808** [comment] 2018-01-04 04:50
+1 I'm getting this as well. `netstat -atu | grep -i rai` shows no results, `lsof -i | grep -i listen` shows no results.

There does not appear to be anything bound to ports 7075/7075 tcp/udp, but the RaiBlocks wallet software still errors out saying "Address in use".

I'm on Mac OS Sierra 10.12.6 (16G29) running Raiblocks v9.0.0 Darwin. The log files located at ~/Library/RaiBlocks/log/* do not get written to when this error occurs. I've observed this by running a tail of the whole dir: `tail -f ~/Library/RaiBlocks/log/*`.

I've tried renaming the `config.json` file, the `data.ldb` file, deleting and reinstalling the software, and deleting the whole ~/Library/RaiBlocks directory, but to no avail.

**Comment by lalanza808** [comment] 2018-01-04 05:25
The plot thickens.

```
$ netstat -n | grep 7075
udp46  43188      0  *.7075                 *.*
$ lsof -i udp:7075
```

Even when there's no rai* processes running, something is binding to udp 7075, but I cannot find it....

**Comment by Dekoze** [comment] 2018-01-05 04:15
I'm unable to reproduce this bug with release V9.0 on OSX 10.13. Seems like netstat has different flags on OSX so the `netstat -atu` won't show what we want. @lalanza808 can you repeat but using `sudo lsof -i udp:7075`. Also can you paste the log associated when you open and close the wallet successfully after a reboot.

**Comment by typistX** [comment] 2018-01-05 23:42
I'm experiencing the same issue with 9 and MacOS 10.13.2. Tried deleting and re-installing. nada.

**Comment by lalanza808** [comment] 2018-01-07 20:55
@Dekoze `sudo lsof -i udp:7075` shows no results - nothing is bound to the udp port.

I made the config update and rebooted - the wallet works properly temporarily. See the gist for log output: https://gist.github.com/lalanza808/cd4c89c6932acac5da5642ee5210e92f

It works for a while, opens, closes, opens again, persists through hibernation, but several hours later once it closes it never opens up again until I reboot. It also doesn't log anything in this current state - just errors out without logging.

<img width="508" alt="image" src="https://user-images.githubusercontent.com/4086248/34653991-005198b6-f3aa-11e7-9e7d-31ac4b365240.png">

**Comment by Dekoze** [comment] 2018-01-08 05:08
Using `netstat -nv` on OS X should list the pid for the port. Can also check if the old rai_wallet is still running with `ps aux | grep rai`. This could be related to #395 but I still haven't been able to reproduce it on any os.

**Comment by lalanza808** [comment] 2018-01-08 05:20
so, these netstat options find the process that lsof will not reveal:

```
$ netstat -nv | grep 7075
udp46 173948      0  *.7075                 *.*                                196724   9216   1939      0
```

However, this process apparently doesn't exist:

```
$ ps aux | grep 1939
# nothin
```

Not sure, I think I'm just going to live with having to reboot whenever the wallet/node dies and just wait patiently for a better version.

**Comment by dylanseago** [comment] 2018-01-12 21:03
This SO thread appears to have a suggested fix: https://stackoverflow.com/questions/40512274/release-udp-port-used-by-dead-process-on-os-x

**Comment by dylanseago** [comment] 2018-01-12 21:09
Also related: https://stackoverflow.com/questions/11876152/mac-firewall-prevents-from-closing-multiple-multicast-udp-ports-properly

**Comment by typistX** [comment] 2018-01-14 17:10
@dylanseago so is it an OS X specific *bug*, or a Raiblocks wallet one? Also, did you manage to solve this for yourself?

**Comment by dylanseago** [comment] 2018-01-29 05:19
@typistX It appears to be an OSX bug. There is probably a workaround that RaiBlocks can implement but I haven't been able to find a fix myself.

**Comment by sciedou** [comment] 2018-02-18 16:30
getting this on Win64 v10.0.1 aswell

**Comment by itsaphel** [comment] 2018-03-01 11:43
Getting on OS X latest version, v10.0.1 rai, exact same issue as listed above and same output of commands.

**Comment by djkomong** [comment] 2018-03-05 23:18
Same issue here! I have version 10 running on mac. Everything was running fine before I updated to version 10.

**Comment by davidwong94** [comment] 2018-04-30 04:46
Any solution for this problem? I'm experiencing this on v12.1 wallet.

**Closed** 2018-05-03 17:38 UTC
